language: r
assert: false
r_packages:
 - knitr
 - testthat
 - pander
 - XML
 - assertthat
 - stringi
 - rvest
 - data.table
 - magrittr
 - xml2
 - devtools
r_github_packages:
 - RTCGA/RTCGA.rnaseq
 - RTCGA/RTCGA.clinical
 - RTCGA/RTCGA.mutations
bioc_packages:
 - Biobase
sudo: required
