# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
r_packages:
 - knitr
 - testthat
 - pander
 - XML
 - assertthat
 - stringi
 - rvest
 - data.table
 - magrittr
 - xml2
 - devtools
sudo: required
