language: r
assert: false
r_packages:
 - knitr
 - testthat
 - pander
 - XML
 - assertthat
 - stringi
 - rvest
 - data.table
 - magrittr
 - xml2
 - devtools
 - rmarkdown
 - survminer
 - dplyr
 - survival
 - ggplot2
r_github_packages:
 - RTCGA/RTCGA.rnaseq
 - RTCGA/RTCGA.clinical
 - RTCGA/RTCGA.mutations
 - RTCGA/RTCGA.CNV
 - RTCGA/RTCGA.PANCAN12
bioc_packages:
 - Biobase
 - GenomicRanges
 - IRanges
 - S4Vectors
sudo: required
