language: r
assert: false
r_packages:
 - knitr
 - testthat
 - pander
 - XML
 - assertthat
 - stringi
 - rvest
 - data.table
 - magrittr
 - xml2
 - devtools
 - dplyr
 - survival
 - ggplot2
 - tidyr
 - rmarkdown
 - ggthemes
 - purrr
r_github_packages:
 - RTCGA/RTCGA.rnaseq
 - RTCGA/RTCGA.clinical
 - RTCGA/RTCGA.mutations
 - RTCGA/RTCGA.CNV
 - RTCGA/RTCGA.PANCAN12
 - RTCGA/RTCGA.RPPA
 - RTCGA/RTCGA.mRNA
 - RTCGA/RTCGA.miRNASeq
 - RTCGA/RTCGA.methylation
 - kassambara/survminer
 - vqv/ggbiplot
bioc_packages:
 - Biobase
 - GenomicRanges
 - IRanges
 - S4Vectors
sudo: required
